CREATE TABLE TEST_MASTER 
    (
     TEST_ID INTEGER NOT NULL , 
     TEST_NAME VARCHAR (500) NOT NULL , 
     TEST_DATE DATE NOT NULL , 
     EMP_TYPE CHAR (50) NOT NULL ,
     CONSTRAINT TEST_MASTER_PK PRIMARY KEY (TEST_ID)
    );

